# Generated by Django 5.0 on 2023-12-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=300)),
                ('lName', models.CharField(max_length=300)),
                ('amount', models.CharField(blank=True, default='0')),
                ('phoneNo', models.CharField(default='0')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
